[theme]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 8501
headless = true
