[aman]
username = "admin"
password = "Youssef123$"
host = "adva-warehouse.c45dykr9xlqi.eu-west-3.rds.amazonaws.com"
port = "3306"
database = "aman_v_2"

[zoho]
username = "admin"
password = "Youssef123$"
host = "adva-warehouse.c45dykr9xlqi.eu-west-3.rds.amazonaws.com"
port = "3306"
database = "zoho"

[Rule_based]
DB_USERNAME = "admin"
DB_PASSWORD = "Youssef123$"
DB_HOST = "adva-warehouse.c45dykr9xlqi.eu-west-3.rds.amazonaws.com"
DB_PORT = "3306"
DB_NAME = "Rule_based"

[credentials.usernames]
admin = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918" 
user1 = "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3" 
